### ISSUE TITLE
/sys/devices/virtual/thermal/thermal_zone0/temp does not always exists

### ISSUE THREAD

**Issue by olaulau** [OpenMediaVault-Plugin-Developers/openmediavault-cputemp#1]
Hi ;
on some hardware, event after running sensors-detect, and having many values of motherboard with sensors, this file does not exists (the "thermal_zone0" doesn't exists at all).

informations :
debian 11
OMV 6
kernel 5.18.0-0.deb11.4-amd64
motherboard : MS-7A38/B450M PRO-VDH MAX (MS-7A38), BIOS B.G0 07/26/2022
cpu : AMD Ryzen 5 5600X

**Comment by ryecoaaron** [comment]
lm-sensors doesn't create the thermal zone (/sys/devices/virtual/thermal/thermal_zone0/temp).  lm-sensors was added to plugin to provide output on systems that are non-standard and don't have a cpu temp at /sys/devices/virtual/thermal/thermal_zone0/temp
