### ISSUE TITLE
Circle status for tempuratue is useless.

### ISSUE THREAD

**Issue by lessload** [OpenMediaVault-Plugin-Developers/openmediavault-cputemp#2]
Why we need to see temperature in circle status ?
It useless and waste dashboard area.
- Dev should consider about it.
- Temperature status like Pi-hole will be better. ( change color to red when more than 70 C )

**Comment by ryecoaaron** [comment]
The widget is the same size regardless and I got quite bit of feedback where people preferred this. 70 C might be fine on some systems, low on another, and above max on others. So, the color change is very difficult.
