### ISSUE TITLE
AMD 5600 G no cpu temp

### ISSUE THREAD

**Issue by edgd1er** [OpenMediaVault-Plugin-Developers/openmediavault-cputemp#4]
plugin is looking for `/sys/devices/virtual/thermal/thermal_zone0/temp` but there is no such information with this cpu.
`cat: /sys/devices/virtual/thermal/thermal_zone0/temp: No file or folder `

Could you add another way to get cpu temperature when the first one fails ?
the command I'm using at the moment is here under:
`$cmd = new \OMV\System\Process("sensors |grep -oP '(?<=Tctl: )\s+\+([0-9\.]+)' | grep -P '[0-9\.]'");`

```
================================================================================
= OS/Debian information
================================================================================
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 11 (bullseye)
Release: 11
Codename: bullseye

================================================================================
= openmediavault information
================================================================================
Release: 6.1.7-1

processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 25
model		: 80
model name	: AMD Ryzen 5 5600G with Radeon Graphics
stepping	: 0
```

**Comment by edgd1er** [comment]
the issue was written yesterday, submitted today, in the meantime I found that there is an evolution in code, allowing to override the cpu temp command and divisor to provide specific settings.

The latest version allows to use env var to override the command to get temperature.
I suppose that would be the way to have a proper cpu monitoring.
 I would have to set the `OMV_CPU_TEMP_COMMAND` and `OMV_CPU_TEMP_DIVISOR`

Is there a documentation about the plugins you could guide me to ?
Thanks for your plugin.

**Comment by ryecoaaron** [comment]
The new changes were released yesterday and I wrote a guide (just happens the example is for a Ryzen cpu) in the forum - https://forum.openmediavault.org/index.php?thread/45959-guide-custom-cpu-temp-script-for-openmediavault-cputemp-plugin/&postID=335916#post335916
