### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by ThirtySomething** [OpenMediaVault-Plugin-Developers/openmediavault-cputemp#5]
Hi there, is there any chance to get statistic information about the cpu temperature? The disk stats plugin provides some RRD graphs (Diagnostics -> Performance statistics) to visualize the measurements. It would be interesting to see the cpu temperature behaviour over the time. Then it might be possible to adjust the timing of scheduled tasks and things like that. And if so, might this be also possible for the S.M.A.R.T. values of the disks (Temperature monitoring)? There is also a temperature measured, but not visible over the time.

**Comment by ryecoaaron** [comment]
I didn't have any plans to add statistics (I have monitoring disabled on all systems).  It would be very difficult to implement for the people that are using custom cpu temp retrieval by parsing the output of the sensors command as well.

smart value statistics would need to be requested from OMV itself.

**Comment by ThirtySomething** [comment]
Okay, thank you for the information. Then I'll request the smart statistics in the OMV repository.
